<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div id="shareto" class="shareto" data-role="share-to-links">
	<ul class="share-list dropdown"></ul>
</div>

<?php
    $_themeHelper = $this->helper('\Unet\SocialShare\Helper\Data');
?>
<script type="text/x-magento-init">
    {
        "[data-role=share-to-links]": {
            "Unet_SocialShare/js/social-share" : {
                "currentStoreUrl": "<?php /* @escapeNotVerified */ echo $_themeHelper->getCurrentStoreUrl(); ?>",
                "config": <?php /* @escapeNotVerified */ echo json_encode($_themeHelper->getShareConfig()); ?>
            }
        }
    }
</script>
